package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "assert_manifest",
    srcs = ["assert_manifest.py"],
    main = "assert_manifest.py",
    python_version = "PY3",
)

py_binary(
    name = "package_omniverse",
    srcs = ["package_omniverse.py"],
    main = "package_omniverse.py",
    python_version = "PY3",
)

exports_files([
    "assert_manifest.py",
    "package_omniverse.py",
])
